apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: quay-push-secret
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    name: vault-sno-mini
    kind: ClusterSecretStore
  target:
    name: quay-push-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: huntreport/quay-push-secret
        property: .dockerconfigjson
