apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-token
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    name: vault-sno-mini
    kind: ClusterSecretStore
  target:
    name: github-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: openshift-gitops/repo-huntreport
        property: password
