apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: git-basic-auth
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    name: vault-sno-mini
    kind: ClusterSecretStore
  target:
    name: git-basic-auth
    creationPolicy: Owner
  data:
    - secretKey: .git-credentials
      remoteRef:
        key: huntreport/git-basic-auth
        property: .git-credentials
    - secretKey: .gitconfig
      remoteRef:
        key: huntreport/git-basic-auth
        property: .gitconfig
