apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
  - pipeline-prod.yaml
  - pipeline-dev.yaml
  - external-secret-quay-push.yaml
  - external-secret-github-token.yaml
  - external-secret-git-basic-auth.yaml
  - cronjob-poll.yaml
